apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o ../helm
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o ../helm
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kong
    spec:
      containers:
        - env:
            - name: KONG_DECLARATIVE_CONFIG
              value: /var/lib/kong/kong.yml
            - name: KONG_DNS_ORDER
              value: LAST,A,CNAME
            - name: KONG_PLUGINS
              value: request-transformer,cors,key-auth,http-log
          image: kong
          name: supabase-kong
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
