apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o ../helm
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: mail
status:
  loadBalancer: {}
