apiVersion: v2
appVersion: v21.10.1
dependencies:
- condition: monitoring.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 13.13.1
description: Redpanda operator helm chart
home: https://vectorized.io
maintainers:
- email: support@vectorized.io
  name: Vectorizedio
name: redpanda-operator
sources:
- https://github.com/vectorizedio/redpanda
type: application
version: v21.10.1
